[lebedev]
git-tree-sha1 = "3be7d910072ca9b568e4647dabcd2f59bb1530c3"

    [[lebedev.download]]
    url = "https://github.com/Liozou/CrystalEnergyGrids.jl/releases/download/lebedev/lebedev.tar.xz"
    sha256 = "12966f1048ea8336b48fd824db2a09c929f2ca2decc8787a45352f455d6666c4"

    [[lebedev.download]]
    url = "https://github.com/Liozou/CrystalEnergyGrids.jl/releases/download/lebedev/lebedev.zip"
    sha256 = "6cdef7e6b7f3df12e278691ce9c33c895e14e5c31feaa5d39cb5044960d140de"
